sudo: false
language: objective-c
osx_image: xcode9

script:
- swift test -Xswiftc -profile-coverage-mapping -Xswiftc -profile-generate

after_success:
- curl -s https://codecov.io/bash > codecov.sh
- chmod +x codecov.sh
- ./codecov.sh -f ./default.profraw
